<header role="header">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse" role="button">
            <span class="sr-only">Toggle Navigation</span>
            
            <span class="icon-bar"></span>
            
            <span class="icon-bar"></span>
            
            <span class="icon-bar"></span>
          </button>

          <a href="#" class="navbar-brand">
            <!-- <img src="./assets/onglet.png"> -->
          Influnias</a>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right js-nav">
            <li><a href="#home">Home</a></li>

            <li><a href="#about">About</a></li>

            <li><a href="#services">Services</a></li>

            <li><a href="#folio">Folio</a></li>

            <li><a href="#testimonials">Testimonials</a></li>

            <li><a href="#contact">Contact</a></li>

            <li><a href="http://alexsblog.org" target="_blank">Blog</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>